language: php 
php: 
 - 5.3
 - 5.4

env:
 - TESTDB=MYSQL CORE_RELEASE=3.0
 - TESTDB=MYSQL CORE_RELEASE=master
 - TESTDB=PGSQL CORE_RELEASE=master

matrix:
  exclude:
    - php: 5.4
      env: TESTDB=PGSQL CORE_RELEASE=master
    - php: 5.4
      env: TESTDB=MYSQL CORE_RELEASE=3.0

before_script:
 - phpenv rehash
 - ./tests/travis/before_script ~/builds/ss 
 - cd ~/builds/ss

script: 
 - phpunit dms/tests/